steps:
  # --------------------------------------------------
  # 1. DEPLOY DAG FILES
  # --------------------------------------------------
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - rsync
      - -r
      - -d
      - airflow/dags/
      - gs://${_COMPOSER_BUCKET}/dags/

  # --------------------------------------------------
  # 2. DEPLOY DATA FILES (SQL, SPARK, CONFIG)
  # --------------------------------------------------
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - rsync
      - -r
      - -d
      - airflow/data/
      - gs://${_COMPOSER_BUCKET}/data/

options:
  logging: CLOUD_LOGGING_ONLY
