substitutions:
  _ENV_NAME: banking-composer-dev
  _REGION: us-central1
  _PYTHON_VERSION: "3"
  _IMAGE_VERSION: "composer-2.6.5-airflow-2.6.3"

steps:

# =====================================================
# 1️⃣ CREATE COMPOSER ENV (IDEMPOTENT)
# =====================================================
- name: gcr.io/cloud-builders/gcloud
  id: create-composer-env
  entrypoint: bash
  args:
    - -c
    - |
      set -e
      if gcloud composer environments describe ${_ENV_NAME} \
        --location ${_REGION} >/dev/null 2>&1; then
        echo "Composer environment already exists"
      else
        echo "Creating Composer environment..."
        gcloud composer environments create ${_ENV_NAME} \
          --location ${_REGION} \
          --image-version ${_IMAGE_VERSION}
      fi

# =====================================================
# 2️⃣ FETCH DAG PREFIX (COMPOSER 2 STYLE)
# =====================================================
- name: gcr.io/cloud-builders/gcloud
  id: fetch-composer-paths
  entrypoint: bash
  args:
    - -c
    - |
      set -e

      DAG_PREFIX=$(gcloud composer environments describe ${_ENV_NAME} \
        --location ${_REGION} \
        --format="value(config.dagGcsPrefix)")

      echo "DAG_PREFIX=${DAG_PREFIX}" >> /workspace/composer.env

      # Extract bucket root (remove /dags)
      BUCKET_ROOT=$(echo ${DAG_PREFIX} | sed 's#/dags$##')

      echo "BUCKET_ROOT=${BUCKET_ROOT}" >> /workspace/composer.env

      cat /workspace/composer.env

# =====================================================
# 3️⃣ DEPLOY DAG FILES (NO EXTRA /dags)
# =====================================================
- name: gcr.io/cloud-builders/gsutil
  id: deploy-dags
  entrypoint: bash
  args:
    - -c
    - |
      source /workspace/composer.env
      gsutil -m rsync -r -d airflow/dags/ ${DAG_PREFIX}

# =====================================================
# 4️⃣ DEPLOY DATA FILES (SQL / SPARK / CONFIG)
# =====================================================
- name: gcr.io/cloud-builders/gsutil
  id: deploy-data
  entrypoint: bash
  args:
    - -c
    - |
      source /workspace/composer.env
      gsutil -m rsync -r -d airflow/data/ ${BUCKET_ROOT}/data/

options:
  logging: CLOUD_LOGGING_ONLY
